### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by mohammad5305** [mohammad5305/pytest.nvim#1]
# TODO

- [x] finding the right docstring for the right function
- [ ] unit tests
- [ ] updating vim help pages
- [ ] more formed usage in main README
